# transport method, support `shm` and `rdma` for now
comm_type = "rdma"

# listener socket for rdma handshake
sender_socket = "127.0.0.1:8001"
receiver_socket = "127.0.0.1:8002"

# channel name for server and client to find each other, the name strings are not matter
stoc_channel_name = "/stoc"
ctos_channel_name = "/stoc"

# buffer size
buf_size = 104857520