[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0"
syn = {version="1.0", features = ["full", "extra-traits", "printing"]}
quote = "1.0"
serde = "1.0"
serde_json = "1.0"
lazy_static = "1.4.0"
measure = { path = "../measure" }

[lib]
proc-macro = true

[dev-dependencies]
cudasys = { path = "../cudasys" }
network = { path = "../network" }
log = "0.4.0"
env_logger = "0.9"
lazy_static = "1.4.0"

[features]
async_api = []
shadow_desc = []
