[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = {version="1.0", features = ["full"]}
quote = "1.0"
serde = "1.0"
serde_json = "1.0"

[lib]
proc-macro = true

[dev-dependencies]
cudasys = { path = "../cudasys" }
network = { path = "../network" }
log = "0.4.0"
lazy_static = "1.4.0"
