[package]
name = "network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codegen = { path = "../codegen" }
libc = "*"
num = "0.2"
num-traits = "0.2"
num-derive = "0.4"
log = "0.4.0"
errno = "0.2.7" 

[dev-dependencies]
cudasys = { path = "../cudasys" }
