[package]
name = "network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codegen = { path = "../codegen" }
libc = "*"
log = "0.4.0"
errno = "0.2.7" 
toml = "0.5"
serde = "1.0"
lazy_static = "1.4.0"
KRdmaKit = { git = "https://github.com/SJTU-IPADS/krcore-artifacts.git", branch = "develop", features = ["user", "OFED_5_4"] }

[dev-dependencies]
cudasys = { path = "../cudasys" }
