# transport method, support `shm` and `rdma` for now
# comm_type = "rdma"
comm_type = "shm"

# listener socket for rdma handshake
sender_socket = "127.0.0.1:8001"
receiver_socket = "127.0.0.1:8002"

# channel name for server and client to find each other, the name strings are not matter
stoc_channel_name = "/stoc"
ctos_channel_name = "/ctos"
stos_channel_name = "/stos"
ctoc_channel_name = "/ctoc"
clocal_channel_name = "/clocal"

# buffer size
buf_size = 4000000000

# network configuration
# bandwidth is in bps, rtt is in ms 
rtt = 0.1
bandwidth = 1073741824